name: Publish release
on:
    release:
        types: [published]
jobs:
    build:
        runs-on: ubuntu-20.04
        strategy:
            matrix:
                node-version: [15]
        steps:
            - uses: actions/checkout@v3
            - uses: fregante/setup-git-user@v1
            - uses: pnpm/action-setup@v2
              with:
                  version: 9
            - name: Use Node.js v18
              uses: actions/setup-node@v3
              with:
                  cache: pnpm
                  node-version: 20.x
            - name: Install dependencies
              run: pnpm install --frozen-lockfile
            - name: Publish
              run: |
                  npm set //registry.npmjs.org/:_authToken $NPM_TOKEN
                  pnpm build
                  pnpm publish --access public --no-git-checks
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
